import Head from "next/head";
import React from "react";
import CardTeammerProfile from '../../src/components/Profile/CardTeammerProfile'
import {IconButton} from "rsuite";
import {HiArrowLeft} from "react-icons/hi";
import Link from 'next/link';
const AddToTeam = () => {

    return (
        <div className="owner">
            <Head>
                <title>Owner login</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <div>
                <div className="breadcrumb-wrapper">
                    <div className="goback-btn">
                        <Link href="/owner/home" passHref>
                                <IconButton
                                    size="lg"
                                    icon={<HiArrowLeft />}
                                    className="goback-btn"
                                />
                        </Link>
                    </div>
                </div>
            </div>
            <div className="teammer-type-banner">
                <div className="product-div">
                    <h3>
                        <h3 className="mr-2">&#128526;</h3>Find people to join your team right now
                    </h3>
                </div>
            </div>
            <p className="text-center my-4" style={{fontSize : '22px'}}>
                You can also add people to your team👇
            </p>
            <div className="row" style={{marginTop : "170px"}}>
                <div className="col-md-4"><CardTeammerProfile isProfile={false}/></div>
                <div className="col-md-4"><CardTeammerProfile isProfile={false}/></div>
                <div className="col-md-4"><CardTeammerProfile isProfile={false}/></div>
            </div>
        </div>
    )

}

export default AddToTeam