import Head from 'next/head';
import '../src/axios-interceptor'
// import Link from "next/link";
import Content from './../src/components/common/Content';
import {useSelector} from "react-redux";
import Router from "next/router";
import {useEffect} from "react";
import {getSession, useSession} from 'next-auth/react'
import getAuth from "../lib/session";

export default function Home(props) {
    const store = useSelector(store => store);
    // const {data: session} = useSession();

    console.log(props)
    // useEffect(() => {
    //     if (store.isAuth === "TEAMMER_TYPE") {
    //         Router.replace("/teammer/home");
    //     } else if (store.isAuth === "STARTUP_TYPE") {
    //         Router.replace("/owner/home")
    //     }
    // }, []);
    return (
        <div>
            <Head>
                <title>Teammer</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <Content/>
        </div>
    )
}
Home.layout = true;

export const getServerSideProps = (context) => {
    const auth = getAuth(context);
    if (auth === "1")
        return {
            redirect: {
                destination: "/owner/home",
                permanent: false,
            },
        };
    else if (auth === "2")
        return {
            redirect: {
                destination: "/teammer/home",
                permanent: false,
            },
        };
    return {
        props: {
            data: 'ajksndkajjsnd',
            protected : false
        }
    }
}