import Head from 'next/head';
import '../src/axios-interceptor';
import Content from './../src/components/common/Content';
import { useSelector } from "react-redux";
import Router from "next/router";
import { useEffect } from "react";

export default function Home({ props }) {
    const store = useSelector(store => store);

    useEffect(() => {
        console.log(localStorage.getItem('type'))
        if (localStorage.getItem('type') === "2") {
            Router.replace("/teammer/home");
        }
        else if (localStorage.getItem('type') === "1") {
            Router.replace("/owner/home")
        }
    }, [store.isAuth]);
    return (
        <div>
            <Head>
                <title>Teammer</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Content />
        </div>
    )
}

